name: Warn about changes to ./.GISTs

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
    paths:
      - '.GISTS'
      - '.GISTS/**'
      
jobs:
  warning:
    runs-on: ubuntu-latest
    steps:
    - name: Warning message
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Warning! direct changes to ./.GISTs will be overwritten after merge by pr-merged.yml'
          })
